# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Publications
    url: '#featured'
    weight: 20
  - name: Work in Progress
    url: '#projects'
    weight: 30
  - name: Other Contributions
    url: ''
    #url: '#posts'
    identifier: "others"
    weight: 40
  - name: Blogs
    parent: others
    url: 'post/blogs'
    #url: '#posts'
    weight: 10
  - name: Comments in the Media
    parent: others
    url: 'post/comments'
    #url: '#posts'
    weight: 20
  - name: Review Articles
    parent: others
    url: 'post/review'
    #url: '#posts'
    weight: 30
  - name: Others
    parent: others
    url: 'post/others'
    #url: '#posts'
    weight: 40
  - name: Teaching
    url: '#teaching'
    weight: 50
  - name: Events
    url: '#events'
    weight: 60
  - name: CV
    url: uploads/resume.pdf
    weight: 70
  - name: Contact
    url: '#contact'
    weight: 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  
